# nixpacks.toml
[phases.setup]
aptPkgs = ["libgl1", "ffmpeg"]

[phases.install]
cmds = [
    "pip install -r requirements.txt" # Ensure huggingface-hub is in requirements.txt
]

[phases.build]
cmds = [
    "huggingface-cli download ByteDance/LatentSync-1.5 whisper/tiny.pt --local-dir checkpoints",
    "huggingface-cli download ByteDance/LatentSync-1.5 latentsync_unet.pt --local-dir checkpoints"
]